from dotenv import load_dotenv
import os

# Загружаем переменные из .env файла
load_dotenv()

EDGE_DRIVER_PATH = os.getenv('EDGE_DRIVER_PATH')

START_URL = os.getenv('START_URL')
SECOND_URL = os.getenv('SECOND_URL')

TELEGRAM_BOT_TOKEN = os.getenv('TELEGRAM_BOT_TOKEN')
TELEGRAM_CHAT_ID = os.getenv('TELEGRAM_CHAT_ID')

TEST_ACCOUNT_USERNAME = os.getenv('TEST_ACCOUNT_USERNAME')
TEST_ACCOUNT_PASSWORD = os.getenv('TEST_ACCOUNT_PASSWORD')

APPLICATION_RUN_TIME = os.getenv('APPLICATION_RUN_TIME')
SEND_STATUS_NOTIFICATION_TIME = os.getenv('SEND_STATUS_NOTIFICATION_TIME')
